name: Notify on Push or Pull Request

on:
  push:
    branches:
      - main # Triggers on any branch
  pull_request:
    types: [opened, edited, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }} # If you have enabled 2FA then you need to generate an App password from Sercurity Sections on Google
          subject: 'GitHub Alert: Code Push or Pull Request'
          body: |
            A new push or pull request has been made to the repository.
            Repository: ${{ github.repository }}
            Event: ${{ github.event_name }}
            Branch: ${{ github.ref }}
            Sender: ${{ github.actor }}
          to: 'intern61techcurve@gmail.com'  # Replace with the recipient's email
          from: ${{ secrets.EMAIL_USERNAME }}  # Replace with the sender's emai
