name: "Build Android App"

on: 
  push:
    branches:
      - main
      - dev
      - prod
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33  # Set the API level according to your project needs
          build-tools: 33.0.0
          ndk-version: 21.4.7075529  # Adjust NDK version as per your needs

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Adjust the Node.js version if needed

      # - name: Set up environment file
      #   run: |
      #     if [ "${{ github.ref }}" == "refs/heads/main" ]; then
      #       cp .env.prod .env
      #     elif [ "${{ github.ref }}" == "refs/heads/dev" ]; then
      #       cp .env.development .env
      #     elif [ "${{ github.ref }}" == "refs/heads/staging" ]; then
      #       cp .env.staging .env
      #     fi

      - name: Install Node.js dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Install Android dependencies
        run: |
          yarn android-clean
          yarn android:dependencies

      - name: Build Android application
        run: |
          cd android
          # ./gradlew assembleRelease
          # bundleRelease for aab
          ./gradlew bundleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.aab
          path: android/app/build/outputs/bundle/release/app-release.aab
          retention-days: 3