name: "Build and Deploy Android App"

on: 
  push:
    branches:
      - dev
      - prod
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: 33.0.0
          ndk-version: 21.4.7075529

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Node.js dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Set Environment File
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/dev' ]]; then
            export ENVFILE=.env.dev
          elif [[ ${{ github.ref }} == 'refs/heads/prod' ]]; then
            export ENVFILE=.env.prod
          else
            export ENVFILE=.env
          fi

      - name: Clean Gradle build
        run: |
          cd android
          ./gradlew clean

      - name: Build Android application
        run: |
          cd android
          ENVFILE=$ENVFILE ./gradlew assembleRelease --scan --info

      - name: Upload AAB as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.aab
          path: android/app/build/outputs/bundle/release/app-release.aab
          retention-days: 3

      - name: Deploy to Play Store
        env:
          GOOGLE_PLAY_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
        run: |
          cd android
          bundle exec fastlane deploy